name: Yizhe Blog
description:
meta_description: Yizhe Blog
permalink: /posts/:year/:month/:day/:title

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://yezersky.github.io"
google_analytics: "UA-71108561-3"
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            "http://yezersky.github.io"
author:         "Yizhe"
